config/routes.rb
Assignment::Application.routes.draw do
  resources :employees, only: ["index", "new", "create"] do
    collection do
      match "group"
      match "sort"
      match "search"
    end
  end
  
  get "/:id/delete", to: "employees#delete", as: :delete_employee

  root :to => 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :age, :department, :designation, :email_id, :location, :name, :soft_deleted

  default_scope where(soft_deleted: false)
  scope :search, ->(keyword) {where("name LIKE '%#{keyword}%' or location LIKE '%#{keyword}%' or email_id LIKE '%#{keyword}%' or designation LIKE '%#{keyword}%' or department LIKE '%#{keyword}%' or age LIKE '%#{keyword}%'")}
  
  validates :name, :age, :department, :designation, :email_id, :location, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  # List of all Employees
  def index
    @employees = Employee.all#where(soft_deleted: false)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(params[:employee])

    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created.'
    else
      render action: "new"
    end
  end

  # Soft Delete, will update soft_deleted attribute to TRUE
  def delete
    begin
      employee = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to employees_path, notice: "Employee with ID #{params[:id]} is not found." and return
    end
    employee.update_attributes(soft_deleted: true)
    redirect_to employees_path, notice: 'Employee was successfully deleted.'
  end
  
  # return Hash with key as grouped attribute & Value as Arrays of grouping result
  def group
    if request.xhr?
      @group_employees = Employee.all.to_set.classify { |emp| emp.send(params[:attribute]) }#Employee.where(soft_deleted: false).group_by {|x| x.send(params[:attribute])}(Another Way)
    end
  end
  
  # search defined as scope in Employee class
  def search
    if request.xhr?
      @employees = Employee.search(params[:keyword])#.where(soft_deleted: false)(Default Scope is used now)
    end
  end
  
  def sort
    if request.xhr?
      @employees = Employee.order(params[:attribute] + " " + params[:order])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  
  # return select fields of Model's attributes for Select Tag(In Future if attributes added, i will be dynamic)
  def select_attributes
    select_list = Employee.attribute_names.reject { |attr| ["id", "created_at", "updated_at", "soft_deleted"].include?(attr)}
    select_list.inject([]) {| result, attr| result.append([attr, attr])}
  end
end

app/views/common/_navigation.html.erb
<div>
  <%= link_to "Employee Group", group_employees_path %>
  <%= link_to "Employee Sort", sort_employees_path %>
  <%= link_to "Employee Search", search_employees_path %>
</div>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br />
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_group_result.html.erb
<h2>Result</h2></br>

<table>
  <tr>
    <th><%= "Group by Attribute: " + params[:attribute] %></th>
    <th>Name( Just for example name else we can have other attributes also)</th>
  </tr>
  
  <% @group_employees.each_pair do |key, value| %>
    <tr>
      <td><%= key %></td>
      <td>
      <% value.each do |emp| %>
        <%= emp.name %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/employees/group.html.erb
<%= form_tag(group_employees_path, remote:true) do %>
  Select Attribute for Grouping Employees : <%= select_tag "attribute", options_for_select(select_attributes) %>
  <%= submit_tag "Submit"  %>
<% end %>
  
<div id="group_result"></div>

app/views/employees/group.js.erb
$("#group_result").html("<%= escape_javascript(render(:partial => 'group_result')) %>");

app/views/employees/index.html.erb
<%= flash[:notice] if flash[:notice] %>
<h1>Listing employees</h1>

<table id="employees_list">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Email</th>
    <th>Location</th>
    <th>Department</th>
    <th>Designation</th>
    <th></th>
  </tr>

<% unless @employees.size == 0  %>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.age %></td>
      <td><%= employee.email_id %></td>
      <td><%= employee.location %></td>
      <td><%= employee.department %></td>
      <td><%= employee.designation %></td>
      <td><%= link_to 'Delete', delete_employee_path(employee), data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% else %>
  <tr><td>No Data Found.</td></tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/search.html.erb
<%= form_tag(search_employees_path, remote:true) do %>
  Enter keyword to search: <%= text_field_tag "keyword" %>
  <%= submit_tag "Search"  %>
<% end %>
  
<div id="search_result"></div>

app/views/employees/search.js.erb
$("#search_result").html("<%= escape_javascript(render(:template => 'employees/index')) %>");

app/views/employees/sort.html.erb
<%= form_tag(sort_employees_path, remote:true) do %>
  Select Attribute for Sort : <%= select_tag "attribute", options_for_select(select_attributes) %></br>
  Select Order: <%= select_tag "order", options_for_select([["Ascending", "asc"], ["Descending", "desc"]]) %></br>
  <%= submit_tag "Submit"  %>
<% end %>
  
<div id="sort_result"></div>

app/views/employees/sort.js.erb
$("#sort_result").html("<%= escape_javascript(render(:template => 'employees/index')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: '/common/navigation' %>
<%= yield %>

</body>
</html>